// src/views/modules/components/EditorFooterActions.tsx
import { AuditOutlined, CloseOutlined, SaveOutlined } from '@ant-design/icons'
import Button from 'antd/es/button'
import Space from 'antd/es/space'

interface Props {
  canSave: boolean
  canAudit: boolean
  saving: boolean
  onCancel: () => void
  onSave: (audit: boolean) => void
}

export function EditorFooterActions({
  canSave,
  canAudit,
  saving,
  onCancel,
  onSave,
}: Props) {
  return (
    <Space>
      <Button
        className="overlay-action-button"
        icon={<CloseOutlined />}
        onClick={onCancel}
      >
        取消
      </Button>
      {canSave && (
        <Button
          type="primary"
          className="overlay-action-button"
          icon={<SaveOutlined />}
          loading={saving}
          onClick={() => onSave(false)}
        >
          保存
        </Button>
      )}
      {canAudit && (
        <Button
          type="primary"
          className="overlay-action-button"
          icon={<AuditOutlined />}
          loading={saving}
          onClick={() => onSave(true)}
        >
          保存并审核
        </Button>
      )}
    </Space>
  )
}

// src/views/modules/components/EditorFooterActions.vue
<script setup lang="ts">
defineProps<{
  canSave: boolean
  canAudit: boolean
  saving: boolean
}>()

const emit = defineEmits<{
  cancel: []
  save: [audit: boolean]
}>()
</script>

<template>
  <a-button class="overlay-action-button" @click="emit('cancel')">取消</a-button>
  <a-button
    v-if="canSave"
    type="primary"
    class="overlay-action-button"
    :loading="saving"
    @click="emit('save', false)"
  >
    保存
  </a-button>
  <a-button
    v-if="canAudit"
    type="primary"
    class="overlay-action-button"
    :loading="saving"
    @click="emit('save', true)"
  >
    保存并审核
  </a-button>
</template>
