// src/views/system/RoleActionEditor.tsx
import { useState, useCallback, useMemo } from 'react'
import {
  Card, Button, Table, Modal, Form, Input, Select, Space, Checkbox,
  Tag, Typography, Empty, Radio, message, Row, Col,
} from 'antd'
import {
  PlusOutlined, SafetyCertificateOutlined,
  UnorderedListOutlined, AppstoreOutlined, CheckSquareOutlined,
  BorderOutlined,
} from '@ant-design/icons'
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import {
  listSystemMenus, listRoleSettingsPage, getRoleActions,
  updateRoleActions, updateRole, createRole,
  type MenuNode, type RoleRecord,
} from '@/api/role-actions'
import { usePermissionStore } from '@/stores/permissionStore'
import { useRequestError } from '@/hooks/useRequestError'
import {
  enabledStatusValues, roleDataScopeValues, roleTypeValues,
} from '@/constants/module-options'
import { normalizeAction, resolveResourceKey } from '@/constants/resource-permissions'

const ACTION_LABELS: Record<string, string> = {
  read: '查看', create: '新增', update: '编辑', delete: '删除',
  audit: '审核', export: '导出', print: '打印', manage_permissions: '配置权限',
}

const ALL_ACTIONS = ['read', 'create', 'update', 'delete', 'audit', 'export', 'print', 'manage_permissions'] as const

export function RoleActionEditor() {
  const queryClient = useQueryClient()
  const { showError } = useRequestError()
  const permissionStore = usePermissionStore()

  const canCreateRole = useMemo(() => permissionStore.can('role', 'create'), [permissionStore])
  const canEditRole = useMemo(() => permissionStore.can('role', 'update'), [permissionStore])
  const canEditPermissions = useMemo(() => permissionStore.can('role', 'manage_permissions'), [permissionStore])

  const [selectedRoleId, setSelectedRoleId] = useState<string | null>(null)
  const [selectedActions, setSelectedActions] = useState<Set<string>>(new Set())
  const [viewMode, setViewMode] = useState<'list' | 'matrix'>('list')

  const [roleModalOpen, setRoleModalOpen] = useState(false)
  const [editingRole, setEditingRole] = useState<RoleRecord | null>(null)
  const [roleForm] = Form.useForm()

  const [roleSaving] = useState(false)

  const { data: rolesData } = useQuery({
    queryKey: ['role-settings'],
    queryFn: async () => {
      const allRoles: RoleRecord[] = []
      let page = 0
      while (true) {
        const data = await listRoleSettingsPage(page, 100)
        allRoles.push(...(data.records || []))
        const totalPages = Number(data.totalPages || 0)
        if ((totalPages > 0 && page + 1 >= totalPages) || (data.records || []).length < 100) break
        page++
      }
      return allRoles
    },
  })

  const roles = useMemo(() => rolesData || [], [rolesData])

  const { data: menuTree = [] } = useQuery({
    queryKey: ['role-permission-options'],
    queryFn: listSystemMenus,
    enabled: canEditPermissions,
  })

  const selectedRoleInfo = useMemo(() => roles.find((r) => r.id === selectedRoleId), [roles, selectedRoleId])

  const flatMenus = useMemo(() => {
    const result: { menuCode: string; menuName: string; parentName: string; resource: string; actions: string[] }[] = []
    for (const group of menuTree) {
      if (group.children.length > 0) {
        for (const child of group.children) {
          if (child.actions.length > 0) {
            result.push({
              menuCode: child.menuCode, menuName: child.menuName,
              parentName: group.menuName, resource: resolveResourceKey(child.menuCode),
              actions: child.actions,
            })
          }
        }
      } else if (group.actions.length > 0) {
        result.push({
          menuCode: group.menuCode, menuName: group.menuName,
          parentName: '', resource: resolveResourceKey(group.menuCode),
          actions: group.actions,
        })
      }
    }
    return result
  }, [menuTree])

  const matrixData = useMemo(() => {
    return flatMenus.map((menu) => {
      const row: Record<string, unknown> = {
        key: menu.menuCode, menuName: menu.menuName, menuCode: menu.menuCode,
        resource: menu.resource, actions: menu.actions,
      }
      let count = 0
      for (const action of ALL_ACTIONS) {
        const supported = menu.actions.includes(action)
        const checked = supported && selectedActions.has(`${menu.resource}:${action}`)
        row[action] = checked
        if (checked) count++
      }
      row._count = `${count}/${menu.actions.length}`
      return row
    })
  }, [flatMenus, selectedActions])

  const selectRole = useCallback(async (role: RoleRecord) => {
    setSelectedRoleId(role.id)
    try {
      const actions = new Set<string>()
      for (const item of await getRoleActions(role.id)) {
        actions.add(`${item.resource}:${normalizeAction(item.action)}`)
      }
      setSelectedActions(actions)
    } catch (err) {
      setSelectedActions(new Set())
      showError(err, '加载角色权限失败')
    }
  }, [showError])

  const isMenuChecked = useCallback((menuCode: string) => {
    const resource = resolveResourceKey(menuCode)
    for (const key of selectedActions) { if (key.startsWith(resource + ':')) return true }
    return false
  }, [selectedActions])

  const isMenuFullyChecked = useCallback((menu: MenuNode) => {
    const resource = resolveResourceKey(menu.menuCode)
    return menu.actions.every((action) => selectedActions.has(`${resource}:${action}`))
  }, [selectedActions])

  const isMenuPartiallyChecked = useCallback((menu: MenuNode) => {
    return isMenuChecked(menu.menuCode) && !isMenuFullyChecked(menu)
  }, [isMenuChecked, isMenuFullyChecked])

  const toggleAction = useCallback((menuCode: string, action: string) => {
    if (!canEditPermissions) { message.warning('暂无权限配置编辑权限'); return }
    const key = `${resolveResourceKey(menuCode)}:${action}`
    const newSet = new Set(selectedActions)
    if (newSet.has(key)) newSet.delete(key); else newSet.add(key)
    setSelectedActions(newSet)
  }, [canEditPermissions, selectedActions])

  const isActionSelected = useCallback((menuCode: string, action: string) => {
    return selectedActions.has(`${resolveResourceKey(menuCode)}:${action}`)
  }, [selectedActions])

  const toggleAllMenuActions = useCallback((menu: MenuNode) => {
    if (!canEditPermissions) { message.warning('暂无权限配置编辑权限'); return }
    const newSet = new Set(selectedActions)
    const resource = resolveResourceKey(menu.menuCode)
    const allChecked = menu.actions.every((action) => newSet.has(`${resource}:${action}`))
    for (const action of menu.actions) {
      const key = `${resource}:${action}`
      if (allChecked) newSet.delete(key); else newSet.add(key)
    }
    setSelectedActions(newSet)
  }, [canEditPermissions, selectedActions])

  const selectAll = useCallback(() => {
    if (!canEditPermissions) { message.warning('暂无权限配置编辑权限'); return }
    const newSet = new Set<string>()
    for (const menu of flatMenus) {
      for (const action of menu.actions) newSet.add(`${menu.resource}:${action}`)
    }
    setSelectedActions(newSet)
  }, [canEditPermissions, flatMenus])

  const deselectAll = useCallback(() => {
    if (!canEditPermissions) { message.warning('暂无权限配置编辑权限'); return }
    setSelectedActions(new Set())
  }, [canEditPermissions])

  const saveRoleActionsMutation = useMutation({
    mutationFn: async () => {
      if (!selectedRoleId) return
      const actions = Array.from(selectedActions).map((key) => {
        const [resource, action] = key.split(':')
        return { resource, action }
      })
      await updateRoleActions(selectedRoleId, actions)
    },
    onSuccess: () => { message.success('权限保存成功') },
    onError: (err: Error) => showError(err, '保存失败'),
  })

  const openRoleForm = useCallback((mode: 'create' | 'edit', role?: RoleRecord) => {
    if (mode === 'edit' && role) {
      if (!canEditRole) { message.warning('暂无编辑角色权限'); return }
      setEditingRole(role)
      roleForm.setFieldsValue({
        roleName: role.roleName, roleCode: role.roleCode,
        roleType: role.roleType, dataScope: role.dataScope,
        remark: role.remark || '',
      })
    } else {
      if (!canCreateRole) { message.warning('暂无新增角色权限'); return }
      setEditingRole(null)
      roleForm.resetFields()
      roleForm.setFieldsValue({ roleType: roleTypeValues[1], dataScope: roleDataScopeValues[0] })
    }
    setRoleModalOpen(true)
  }, [canEditRole, canCreateRole, roleForm])

  const saveRoleMutation = useMutation({
    mutationFn: async (values: Record<string, unknown>) => {
      const payload = {
        ...values,
        remark: values.remark || null,
        status: editingRole?.status || enabledStatusValues[0],
      }
      if (editingRole) {
        await updateRole(editingRole.id, payload)
        return { mode: 'edit' as const }
      }
      const response = await createRole(payload)
      return { mode: 'create' as const, data: response.data }
    },
    onSuccess: async (result) => {
      if (result.mode === 'create' && result.data) {
        message.success('角色创建成功')
        setRoleModalOpen(false)
        await queryClient.invalidateQueries({ queryKey: ['role-settings'] })
        const newRole = result.data as RoleRecord
        if (newRole?.id) {
          Modal.confirm({
            title: '角色创建成功',
            content: `角色已创建完成，是否立即为此角色配置权限？`,
            okText: '去配置', cancelText: '稍后配置',
            onOk: () => { const created = roles.find((r) => r.id === newRole.id); if (created) selectRole(created) },
          })
        }
      } else {
        message.success('角色更新成功')
        setRoleModalOpen(false)
        await queryClient.invalidateQueries({ queryKey: ['role-settings'] })
      }
    },
    onError: (err: Error) => showError(err, '保存失败'),
  })

  const handleSaveRole = useCallback(async () => {
    try {
      const values = await roleForm.validateFields()
      if (!values.roleName?.trim() || !values.roleCode?.trim()) {
        message.warning('请填写角色名称和编码')
        return
      }
      saveRoleMutation.mutate(values)
    } catch { /* validation failed */ }
  }, [roleForm, saveRoleMutation])

  const matrixColumns = useMemo(() => {
    const cols = [
      { dataIndex: 'menuName', title: '菜单名称', width: 160, fixed: 'left' as const },
    ] as Array<Record<string, unknown>>
    for (const action of ALL_ACTIONS) {
      const label = ACTION_LABELS[action] || action
      if (!flatMenus.some((m) => m.actions.includes(action))) continue
      cols.push({
        dataIndex: action, title: label, width: 70, align: 'center' as const,
        render: (checked: unknown, record: Record<string, unknown>) => {
          const supported = Array.isArray(record.actions) && (record.actions as string[]).includes(action)
          if (!supported) return <span style={{ color: '#d9d9d9' }}>-</span>
          return (
            <Checkbox
              checked={checked as boolean}
              disabled={!canEditPermissions}
              onChange={() => toggleAction(String(record.menuCode || ''), action)}
            />
          )
        },
      })
    }
    cols.push({ dataIndex: '_count', title: '已授权', width: 70, align: 'center' as const })
    return cols
  }, [flatMenus, canEditPermissions, toggleAction])

  return (
    <div className="page-stack">
      <Row gutter={16} style={{ height: 'calc(100vh - 160px)' }}>
        <Col span={6}>
          <Card
            title="角色列表"
            size="small"
            style={{ height: '100%', display: 'flex', flexDirection: 'column' }}
            styles={{ body: { flex: 1, overflow: 'auto', padding: 8 } }}
            extra={canCreateRole && <Button size="small" type="primary" icon={<PlusOutlined />} onClick={() => openRoleForm('create')}>新增</Button>}
          >
            {roles.map((role) => (
              <div
                key={role.id}
                style={{
                  padding: '12px 16px', borderRadius: 8, cursor: 'pointer', marginBottom: 4,
                  border: selectedRoleId === role.id ? '1px solid #91d5ff' : '1px solid transparent',
                  background: selectedRoleId === role.id ? '#e6f7ff' : undefined,
                }}
                onClick={() => selectRole(role)}
              >
                <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 4 }}>
                  <Typography.Text strong>{role.roleName}</Typography.Text>
                  <Tag color={role.status === enabledStatusValues[0] ? 'green' : 'red'} style={{ marginLeft: 8 }}>{role.status}</Tag>
                </div>
                <div style={{ display: 'flex', gap: 8, fontSize: 12, color: '#8c8c8c' }}>
                  <span>{role.roleCode}</span>
                  <span>{role.roleType}</span>
                  <span>{role.userCount} 用户</span>
                </div>
              </div>
            ))}
            {roles.length === 0 && <Empty description="暂无角色" />}
          </Card>
        </Col>

        <Col span={18}>
          <Card
            size="small"
            style={{ height: '100%', display: 'flex', flexDirection: 'column' }}
            styles={{ body: { flex: 1, overflow: 'auto' } }}
            title={
              <Space>
                <SafetyCertificateOutlined />
                <span>{selectedRoleInfo ? `${selectedRoleInfo.roleName} - 权限配置` : '请选择角色'}</span>
              </Space>
            }
            extra={
              selectedRoleInfo && (
                <Space size="small">
                  {canEditPermissions && <Button size="small" icon={<CheckSquareOutlined />} onClick={selectAll}>全选</Button>}
                  {canEditPermissions && <Button size="small" icon={<BorderOutlined />} onClick={deselectAll}>全不选</Button>}
                  {canEditPermissions && <span style={{ borderLeft: '1px solid #f0f0f0', height: 20 }} />}
                  <Radio.Group size="small" value={viewMode} onChange={(e) => setViewMode(e.target.value)} buttonStyle="solid">
                    <Radio.Button value="list"><UnorderedListOutlined /> 列表</Radio.Button>
                    <Radio.Button value="matrix"><AppstoreOutlined /> 矩阵</Radio.Button>
                  </Radio.Group>
                  <span style={{ borderLeft: '1px solid #f0f0f0', height: 20 }} />
                  {canEditPermissions && <Button type="primary" size="small" loading={saveRoleActionsMutation.isPending} onClick={() => saveRoleActionsMutation.mutate()}>保存权限</Button>}
                </Space>
              )
            }
          >
            {selectedRoleInfo ? (
              viewMode === 'list' ? (
                <div>
                  {menuTree.map((group) => (
                    <div key={group.menuCode} style={{ marginBottom: 16 }}>
                      {group.children.length > 0 && (
                        <div style={{ padding: '8px 0', borderBottom: '1px solid #f0f0f0', marginBottom: 8 }}>
                          <Typography.Text strong>{group.menuName}</Typography.Text>
                        </div>
                      )}
                      {(group.children.length > 0 ? group.children : [group]).filter((m) => m.actions.length > 0).map((child) => (
                        <div key={child.menuCode} style={{ display: 'flex', alignItems: 'center', padding: '6px 0 6px 16px' }}>
                          <div style={{ width: 160, flexShrink: 0 }}>
                            <Checkbox
                              checked={isMenuChecked(child.menuCode)}
                              indeterminate={isMenuPartiallyChecked(child)}
                              disabled={!canEditPermissions}
                              onChange={() => toggleAllMenuActions(child)}
                            >
                              <Typography.Text strong>{child.menuName}</Typography.Text>
                            </Checkbox>
                          </div>
                          <Space size={16} wrap>
                            {child.actions.map((action) => (
                              <Checkbox
                                key={action}
                                checked={isActionSelected(child.menuCode, action)}
                                disabled={!canEditPermissions}
                                onChange={() => toggleAction(child.menuCode, action)}
                              >
                                {ACTION_LABELS[action] || action}
                              </Checkbox>
                            ))}
                          </Space>
                        </div>
                      ))}
                    </div>
                  ))}
                </div>
              ) : (
                <Table
                  rowKey="key"
                  columns={matrixColumns}
                  dataSource={matrixData}
                  size="small"
                  bordered
                  pagination={false}
                  scroll={{ x: 800 }}
                />
              )
            ) : (
              <Empty description="请从左侧选择一个角色来配置权限" style={{ marginTop: 120 }} />
            )}
          </Card>
        </Col>
      </Row>

      <Modal
        title={editingRole ? '编辑角色' : '新增角色'}
        open={roleModalOpen}
        onCancel={() => setRoleModalOpen(false)}
        onOk={handleSaveRole}
        confirmLoading={roleSaving}
        okText="保存"
        cancelText="取消"
        maskClosable={false}
      >
        <Form form={roleForm} layout="vertical">
          <Form.Item name="roleName" label="角色名称" required>
            <Input placeholder="例如：采购主管" maxLength={64} />
          </Form.Item>
          <Form.Item name="roleCode" label="角色编码" required>
            <Input placeholder="例如：PURCHASER" maxLength={64} disabled={!!editingRole} />
          </Form.Item>
          <Form.Item name="roleType" label="角色类型">
            <Select options={roleTypeValues.map((t) => ({ label: t, value: t }))} />
          </Form.Item>
          <Form.Item name="dataScope" label="数据范围">
            <Select options={roleDataScopeValues.map((s) => ({ label: s, value: s }))} />
          </Form.Item>
          <Form.Item name="remark" label="备注">
            <Input.TextArea placeholder="角色描述" rows={3} />
          </Form.Item>
        </Form>
      </Modal>
    </div>
  )
}

// src/views/system/RoleActionEditor.vue
<script setup lang="ts">
import { ref, onMounted, computed, watch } from 'vue'
import { Modal, message } from 'ant-design-vue'
import { useRoute } from 'vue-router'
import {
  PlusOutlined,
  EditOutlined,
  SafetyCertificateOutlined,
  UnorderedListOutlined,
  AppstoreOutlined,
  CheckSquareOutlined,
  BorderOutlined,
} from '@ant-design/icons-vue'
import {
  createRole,
  getRoleActions,
  listSystemMenus as listRolePermissionOptions,
  listRoleSettingsPage,
  updateRole,
  updateRoleActions,
  type MenuNode,
  type RoleRecord,
} from '@/api/role-actions'
import { useRequestError } from '@/composables/use-request-error'
import {
  enabledStatusValues,
  roleDataScopeValues,
  roleTypeValues,
} from '@/constants/module-options'
import { usePermissionStore } from '@/stores/permission'
import { normalizeAction, resolveResourceKey } from '@/constants/resource-permissions'

const ACTION_LABELS: Record<string, string> = {
  read: '查看',
  create: '新增',
  update: '编辑',
  delete: '删除',
  audit: '审核',
  export: '导出',
  print: '打印',
  manage_permissions: '配置权限',
}
const showRequestError = useRequestError()
const route = useRoute()

const ALL_ACTIONS = [
  'read',
  'create',
  'update',
  'delete',
  'audit',
  'export',
  'print',
  'manage_permissions',
] as const
type ActionCode = (typeof ALL_ACTIONS)[number]

const loading = ref(false)
const roles = ref<RoleRecord[]>([])
const selectedRoleId = ref<string | null>(null)
const selectedActions = ref<Set<string>>(new Set())
const saving = ref(false)
const roleSaving = ref(false)
const viewMode = ref<'list' | 'matrix'>('list')

const showRoleModal = ref(false)
const editingRole = ref<RoleRecord | null>(null)
const formRoleName = ref('')
const formRoleCode = ref('')
const formRoleType = ref<string>(roleTypeValues[1])
const formDataScope = ref<string>(roleDataScopeValues[0])
const formRemark = ref('')
const permissionStore = usePermissionStore()
const menuTree = ref<MenuNode[]>([])

const roleTypeOptions = [...roleTypeValues]
const dataScopeOptions = [...roleDataScopeValues]
const canViewRoleCatalog = computed(() =>
  permissionStore.can('role', 'read'),
)
const canCreateRole = computed(() =>
  permissionStore.can('role', 'create'),
)
const canEditRole = computed(() =>
  permissionStore.can('role', 'update'),
)
const canEditPermissions = computed(() =>
  permissionStore.can('role', 'manage_permissions'),
)
const ROLE_PAGE_SIZE = 100

onMounted(() => {
  if (canEditPermissions.value) {
    void loadMenus()
  }
  if (canViewRoleCatalog.value) {
    void loadRoles()
  }
})

watch(
  () => route?.query?.keyword,
  () => {
    void syncSelectedRoleFromQuery()
  },
)

async function loadMenus() {
  try {
    menuTree.value = await listRolePermissionOptions()
  } catch (error) {
    showRequestError(error, '加载菜单失败')
  }
}

async function loadRoles() {
  if (!canViewRoleCatalog.value) {
    roles.value = []
    selectedRoleId.value = null
    selectedActions.value = new Set()
    return
  }
  loading.value = true
  try {
    const mergedRoles: RoleRecord[] = []
    let page = 0
    let partialFailure = false

    while (true) {
      try {
        const data = await listRoleSettingsPage(page, ROLE_PAGE_SIZE)
        const currentPageRoles = data.records || []

        mergedRoles.push(...currentPageRoles)

        const totalPages = Number(data.totalPages || 0)
        if (
          (totalPages > 0 && page + 1 >= totalPages) ||
          currentPageRoles.length < ROLE_PAGE_SIZE
        ) {
          break
        }

        page += 1
      } catch {
        partialFailure = mergedRoles.length > 0
        if (!partialFailure) {
          throw new Error('load_roles_failed')
        }
        break
      }
    }

    roles.value = mergedRoles
    if (
      selectedRoleId.value != null &&
      !mergedRoles.some((role) => role.id === selectedRoleId.value)
    ) {
      selectedRoleId.value = null
      selectedActions.value = new Set()
    }
    if (partialFailure) {
      message.warning('部分角色加载失败，当前仅展示已成功加载的数据')
    }
    await syncSelectedRoleFromQuery()
  } catch (error) {
    showRequestError(error, '加载角色失败')
  } finally {
    loading.value = false
  }
}

function findRoleByKeyword() {
  const keyword = String(route?.query?.keyword || '').trim()
  if (!keyword) {
    return null
  }
  return (
    roles.value.find((role) => role.roleName === keyword)
    || roles.value.find((role) => role.roleCode === keyword)
    || roles.value.find(
      (role) =>
        role.roleName?.includes(keyword) || role.roleCode?.includes(keyword),
    )
    || null
  )
}

async function syncSelectedRoleFromQuery() {
  const matchedRole = findRoleByKeyword()
  if (!matchedRole || matchedRole.id === selectedRoleId.value) {
    return
  }
  await selectRole(matchedRole)
}

async function selectRole(role: RoleRecord) {
  selectedRoleId.value = role.id
  try {
    const actions = new Set<string>()
    for (const item of await getRoleActions(role.id)) {
      actions.add(`${item.resource}:${normalizeAction(item.action)}`)
    }
    selectedActions.value = actions
  } catch (error) {
    selectedActions.value = new Set()
    showRequestError(error, '加载角色权限失败')
  }
}

// ========== 矩阵视图数据 ==========

const flatMenus = computed(() => {
  const result: {
    menuCode: string
    menuName: string
    parentName: string
    resource: string
    actions: string[]
  }[] = []
  for (const group of menuTree.value) {
    if (group.children.length > 0) {
      for (const child of group.children) {
        if (child.actions.length > 0) {
          result.push({
            menuCode: child.menuCode,
            menuName: child.menuName,
            parentName: group.menuName,
            resource: resolveResourceKey(child.menuCode),
            actions: child.actions,
          })
        }
      }
    } else if (group.actions.length > 0) {
      result.push({
        menuCode: group.menuCode,
        menuName: group.menuName,
        parentName: '',
        resource: resolveResourceKey(group.menuCode),
        actions: group.actions,
      })
    }
  }
  return result
})

const matrixColumns = computed(() => {
  const cols = [
    {
      title: '菜单名称',
      dataIndex: 'menuName',
      key: 'menuName',
      width: 160,
      fixed: 'left' as const,
    },
  ]
  for (const action of ALL_ACTIONS) {
    cols.push({
      title: action,
      dataIndex: action,
      key: action,
      width: 70,
      fixed: undefined as unknown as 'left',
    })
  }
  cols.push({
    title: '已授权',
    dataIndex: '_count',
    key: '_count',
    width: 70,
    fixed: undefined as unknown as 'left',
  })
  return cols
})

const matrixData = computed(() => {
  return flatMenus.value.map((menu) => {
    const row: Record<string, unknown> = {
      key: menu.menuCode,
      menuName: menu.menuName,
      menuCode: menu.menuCode,
      resource: menu.resource,
      actions: menu.actions,
    }
    let count = 0
    for (const action of ALL_ACTIONS) {
      const supported = menu.actions.includes(action)
      const checked =
        supported && selectedActions.value.has(`${menu.resource}:${action}`)
      row[action] = checked
      if (checked) count++
    }
    row._count = `${count}/${menu.actions.length}`
    return row
  })
})

// ========== 权限操作函数 ==========

function isMenuChecked(menuCode: string): boolean {
  const resource = resolveResourceKey(menuCode)
  for (const key of selectedActions.value) {
    if (key.startsWith(resource + ':')) return true
  }
  return false
}

function isMenuFullyChecked(menu: MenuNode) {
  const resource = resolveResourceKey(menu.menuCode)
  return menu.actions.every((action: string) =>
    selectedActions.value.has(`${resource}:${action}`),
  )
}

function isMenuPartiallyChecked(menu: MenuNode) {
  return isMenuChecked(menu.menuCode) && !isMenuFullyChecked(menu)
}

function toggleAction(menuCode: string, action: string) {
  if (!canEditPermissions.value) {
    message.warning('暂无权限配置编辑权限')
    return
  }
  const key = `${resolveResourceKey(menuCode)}:${action}`
  const newSet = new Set(selectedActions.value)
  if (newSet.has(key)) {
    newSet.delete(key)
  } else {
    newSet.add(key)
  }
  selectedActions.value = newSet
}

function isActionSelected(menuCode: string, action: string) {
  return selectedActions.value.has(`${resolveResourceKey(menuCode)}:${action}`)
}

function toggleAllMenuActions(menu: MenuNode) {
  if (!canEditPermissions.value) {
    message.warning('暂无权限配置编辑权限')
    return
  }
  const newSet = new Set(selectedActions.value)
  const resource = resolveResourceKey(menu.menuCode)
  const allChecked = menu.actions.every((action: string) =>
    newSet.has(`${resource}:${action}`),
  )
  for (const action of menu.actions) {
    const key = `${resource}:${action}`
    if (allChecked) {
      newSet.delete(key)
    } else {
      newSet.add(key)
    }
  }
  selectedActions.value = newSet
}

// ========== 批量操作 ==========

function selectAll() {
  if (!canEditPermissions.value) {
    message.warning('暂无权限配置编辑权限')
    return
  }
  const newSet = new Set<string>()
  for (const menu of flatMenus.value) {
    for (const action of menu.actions) {
      newSet.add(`${menu.resource}:${action}`)
    }
  }
  selectedActions.value = newSet
}

function deselectAll() {
  if (!canEditPermissions.value) {
    message.warning('暂无权限配置编辑权限')
    return
  }
  selectedActions.value = new Set()
}

function toggleActionColumn(action: string) {
  if (!canEditPermissions.value) {
    message.warning('暂无权限配置编辑权限')
    return
  }
  const newSet = new Set(selectedActions.value)
  const colState = actionColumnState.value[action]
  const allChecked = colState?.allChecked ?? false
  for (const menu of flatMenus.value) {
    if (!menu.actions.includes(action)) continue
    const key = `${menu.resource}:${action}`
    if (allChecked) {
      newSet.delete(key)
    } else {
      newSet.add(key)
    }
  }
  selectedActions.value = newSet
}

const actionColumnState = computed(() => {
  const result: Record<
    string,
    { allChecked: boolean; indeterminate: boolean }
  > = {}
  for (const action of ALL_ACTIONS) {
    const supported = flatMenus.value.filter((m) => m.actions.includes(action))
    if (supported.length === 0) {
      result[action] = { allChecked: false, indeterminate: false }
      continue
    }
    const checkedCount = supported.filter((m) =>
      selectedActions.value.has(`${m.resource}:${action}`),
    ).length
    result[action] = {
      allChecked: checkedCount === supported.length,
      indeterminate: checkedCount > 0 && checkedCount < supported.length,
    }
  }
  return result
})

function toggleMatrixCell(menuCode: string, action: string) {
  toggleAction(menuCode, action)
}

// ========== 保存权限 ==========

async function saveRoleActions() {
  if (!canEditPermissions.value) {
    message.warning('暂无权限配置编辑权限')
    return
  }
  if (!selectedRoleInfo.value || selectedRoleId.value == null) return
  saving.value = true
  try {
    const actions = Array.from(selectedActions.value).map((key) => {
      const [resource, action] = key.split(':')
      return { resource, action }
    })
    await updateRoleActions(selectedRoleId.value, actions)
    message.success('权限保存成功')
  } catch (error) {
    showRequestError(error, '保存失败')
  } finally {
    saving.value = false
  }
}

// ========== 角色 CRUD ==========

function openRoleForm(mode: 'create' | 'edit', role?: RoleRecord) {
  if (mode === 'edit' && role) {
    if (!canEditRole.value) {
      message.warning('暂无编辑角色权限')
      return
    }
    editingRole.value = role
    formRoleName.value = role.roleName
    formRoleCode.value = role.roleCode
    formRoleType.value = role.roleType
    formDataScope.value = role.dataScope
    formRemark.value = role.remark || ''
  } else {
    if (!canCreateRole.value) {
      message.warning('暂无新增角色权限')
      return
    }
    editingRole.value = null
    formRoleName.value = ''
    formRoleCode.value = ''
    formRoleType.value = roleTypeValues[1]
    formDataScope.value = roleDataScopeValues[0]
    formRemark.value = ''
  }
  showRoleModal.value = true
}

function closeRoleForm() {
  showRoleModal.value = false
  roleSaving.value = false
}

async function saveRole() {
  const isEdit = editingRole.value != null
  if (!(isEdit ? canEditRole.value : canCreateRole.value)) {
    message.warning(isEdit ? '暂无编辑角色权限' : '暂无新增角色权限')
    return
  }
  if (!formRoleName.value.trim() || !formRoleCode.value.trim()) {
    message.warning('请填写角色名称和编码')
    return
  }

  roleSaving.value = true
  try {
    const payload: Record<string, unknown> = {
      roleName: formRoleName.value.trim(),
      roleCode: formRoleCode.value.trim(),
      roleType: formRoleType.value,
      dataScope: formDataScope.value,
      remark: formRemark.value.trim() || null,
      status: editingRole.value?.status || enabledStatusValues[0],
    }

    if (isEdit) {
      await updateRole(editingRole.value!.id, payload)
      message.success('角色更新成功')
    } else {
      const response = await createRole(payload)
      message.success('角色创建成功')
      closeRoleForm()
      await loadRoles()
      const newRole = (response as { data?: RoleRecord }).data
      if (newRole?.id) {
        Modal.confirm({
          title: '角色创建成功',
          content: `角色「${payload.roleName}」已创建完成，是否立即为此角色配置权限？`,
          okText: '去配置',
          cancelText: '稍后配置',
          onOk() {
            const created = roles.value.find((r) => r.id === newRole.id)
            if (created) {
              selectRole(created)
            }
          },
        })
      }
      return
    }

    closeRoleForm()
    await loadRoles()
  } catch (error) {
    showRequestError(error, '保存失败')
  } finally {
    roleSaving.value = false
  }
}

const selectedRoleInfo = computed(() =>
  roles.value.find((r) => r.id === selectedRoleId.value),
)

const roleModalTitle = computed(() =>
  editingRole.value ? '编辑角色' : '新增角色',
)

function resolveActionCode(value: unknown): ActionCode | null {
  if (typeof value !== 'string') {
    return null
  }
  return (ALL_ACTIONS as readonly string[]).includes(value) ? value as ActionCode : null
}

function isActionColumn(value: unknown) {
  return resolveActionCode(value) != null
}

function getActionLabel(value: unknown) {
  const action = resolveActionCode(value)
  return action ? ACTION_LABELS[action] || action : String(value || '')
}

function isAnyMenuSupportingAction(value: unknown) {
  const action = resolveActionCode(value)
  return action ? flatMenus.value.some((menu) => menu.actions.includes(action)) : false
}

function getActionColumnCheckState(value: unknown) {
  const action = resolveActionCode(value)
  return action ? actionColumnState.value[action] : undefined
}

function toggleActionColumnByKey(value: unknown) {
  const action = resolveActionCode(value)
  if (action) {
    toggleActionColumn(action)
  }
}

function matrixRowSupportsAction(record: Record<string, unknown>, value: unknown) {
  const action = resolveActionCode(value)
  if (!action || !Array.isArray(record.actions)) {
    return false
  }
  return record.actions.map((item) => String(item)).includes(action)
}

function isMatrixActionSelected(record: Record<string, unknown>, value: unknown) {
  const action = resolveActionCode(value)
  if (!action) {
    return false
  }
  return selectedActions.value.has(`${String(record.resource || '')}:${action}`)
}

function toggleMatrixCellByKey(record: Record<string, unknown>, value: unknown) {
  const action = resolveActionCode(value)
  if (action) {
    toggleMatrixCell(String(record.menuCode || ''), action)
  }
}
</script>

<template>
  <div class="page-stack role-action-editor-page">
    <div class="role-editor-layout">
      <!-- 左侧：角色列表 -->
      <div class="role-list-panel">
        <div class="panel-header">
          <span class="panel-title">角色列表</span>
          <a-button
            v-if="canCreateRole"
            size="small"
            type="primary"
            @click="openRoleForm('create')"
          >
            <template #icon><PlusOutlined /></template>
            新增
          </a-button>
        </div>
        <div class="role-list">
          <div
            v-for="role in roles"
            :key="role.id"
            :class="['role-item', { active: selectedRoleId === role.id }]"
            @click="selectRole(role)"
          >
            <div class="role-item-header">
              <span class="role-name">{{ role.roleName }}</span>
              <a-tag
                :color="role.status === enabledStatusValues[0] ? 'green' : 'red'"
                size="small"
              >
                {{ role.status }}
              </a-tag>
            </div>
            <div class="role-item-meta">
              <span>{{ role.roleCode }}</span>
              <span>{{ role.roleType }}</span>
              <span>{{ role.userCount }} 用户</span>
            </div>
            <div v-if="canEditRole" class="role-item-actions">
              <span
                class="role-edit-link"
                @click.stop="openRoleForm('edit', role)"
              >
                <EditOutlined /> 编辑
              </span>
            </div>
          </div>
          <a-empty v-if="roles.length === 0" description="暂无角色" />
        </div>
      </div>

      <!-- 右侧：权限配置 -->
      <div class="permission-panel">
        <div class="panel-header">
          <div class="panel-header-left">
            <span class="panel-title">
              <SafetyCertificateOutlined />
              {{
                selectedRoleInfo
                  ? `${selectedRoleInfo.roleName} - 权限配置`
                  : canViewRoleCatalog
                    ? '请选择角色'
                    : '缺少角色列表查看权限'
              }}
            </span>
          </div>
          <div v-if="selectedRoleInfo" class="panel-header-right">
            <a-space size="small">
              <a-button
                v-if="canEditPermissions"
                size="small"
                @click="selectAll"
              >
                <template #icon><CheckSquareOutlined /></template>
                全选
              </a-button>
              <a-button
                v-if="canEditPermissions"
                size="small"
                @click="deselectAll"
              >
                <template #icon><BorderOutlined /></template>
                全不选
              </a-button>
              <a-divider v-if="canEditPermissions" type="vertical" />
              <a-radio-group
                v-model:value="viewMode"
                size="small"
                button-style="solid"
              >
                <a-radio-button value="list">
                  <UnorderedListOutlined /> 列表
                </a-radio-button>
                <a-radio-button value="matrix">
                  <AppstoreOutlined /> 矩阵
                </a-radio-button>
              </a-radio-group>
              <a-divider type="vertical" />
              <a-button
                v-if="canEditPermissions"
                type="primary"
                size="small"
                :loading="saving"
                @click="saveRoleActions"
              >
                保存权限
              </a-button>
            </a-space>
          </div>
        </div>

        <!-- 列表视图 -->
        <div v-if="selectedRoleInfo && viewMode === 'list'" class="menu-tree">
          <div v-for="menu in menuTree" :key="menu.menuCode" class="menu-group">
            <div v-if="menu.children.length > 0" class="menu-group-header">
              <span class="menu-group-title">{{ menu.menuName }}</span>
            </div>

            <div
              v-for="child in menu.children"
              :key="child.menuCode"
              class="menu-item-row"
            >
              <div class="menu-item-header">
                <a-checkbox
                  :checked="isMenuChecked(child.menuCode)"
                  :indeterminate="isMenuPartiallyChecked(child)"
                  :disabled="!canEditPermissions"
                  @change="toggleAllMenuActions(child)"
                >
                  <span class="menu-item-name">{{ child.menuName }}</span>
                </a-checkbox>
              </div>
              <div class="action-checkboxes">
                <a-checkbox
                  v-for="action in child.actions"
                  :key="action"
                  :checked="isActionSelected(child.menuCode, action)"
                  :disabled="!canEditPermissions"
                  @change="toggleAction(child.menuCode, action)"
                >
                  {{ ACTION_LABELS[action] || action }}
                </a-checkbox>
              </div>
            </div>

            <div
              v-if="menu.children.length === 0 && menu.actions.length > 0"
              class="menu-item-row"
            >
              <div class="menu-item-header">
                <a-checkbox
                  :checked="isMenuChecked(menu.menuCode)"
                  :indeterminate="isMenuPartiallyChecked(menu)"
                  :disabled="!canEditPermissions"
                  @change="toggleAllMenuActions(menu)"
                >
                  <span class="menu-item-name">{{ menu.menuName }}</span>
                </a-checkbox>
              </div>
              <div class="action-checkboxes">
                <a-checkbox
                  v-for="action in menu.actions"
                  :key="action"
                  :checked="isActionSelected(menu.menuCode, action)"
                  :disabled="!canEditPermissions"
                  @change="toggleAction(menu.menuCode, action)"
                >
                  {{ ACTION_LABELS[action] || action }}
                </a-checkbox>
              </div>
            </div>
          </div>
        </div>

        <!-- 矩阵视图 -->
        <div
          v-if="selectedRoleInfo && viewMode === 'matrix'"
          class="matrix-view"
        >
          <a-table
            :columns="matrixColumns"
            :data-source="matrixData"
            :pagination="false"
            size="small"
            :scroll="{ y: 'calc(100vh - 280px)' }"
            bordered
          >
            <template #headerCell="{ column }">
              <template v-if="isActionColumn(column.key)">
                <div class="matrix-col-header">
                  <a-checkbox
                    v-if="isAnyMenuSupportingAction(column.key)"
                    :checked="getActionColumnCheckState(column.key)?.allChecked ?? false"
                    :indeterminate="getActionColumnCheckState(column.key)?.indeterminate ?? false"
                    :disabled="!canEditPermissions"
                    @change="toggleActionColumnByKey(column.key)"
                  />
                  <span>{{ getActionLabel(column.key) }}</span>
                </div>
              </template>
            </template>
            <template #bodyCell="{ column, record }">
              <template v-if="isActionColumn(column.key)">
                <a-checkbox
                  v-if="matrixRowSupportsAction(record, column.key)"
                  :checked="isMatrixActionSelected(record, column.key)"
                  :disabled="!canEditPermissions"
                  @change="toggleMatrixCellByKey(record, column.key)"
                />
                <span v-else class="matrix-unsupported">-</span>
              </template>
            </template>
          </a-table>
        </div>

        <a-empty
          v-if="!selectedRoleInfo"
          :description="
            canViewRoleCatalog
              ? '请从左侧选择一个角色来配置权限'
              : '当前账号缺少角色列表查看权限'
          "
          style="margin-top: 120px"
        />
      </div>
    </div>

    <!-- 角色编辑弹窗 -->
    <a-modal
      v-model:open="showRoleModal"
      :title="roleModalTitle"
      :mask-closable="false"
      :confirm-loading="roleSaving"
      ok-text="保存"
      cancel-text="取消"
      @ok="saveRole"
      @cancel="closeRoleForm"
    >
      <a-form layout="vertical">
        <a-form-item label="角色名称" required>
          <a-input
            v-model:value="formRoleName"
            placeholder="例如：采购主管"
            :maxlength="64"
          />
        </a-form-item>
        <a-form-item label="角色编码" required>
          <a-input
            v-model:value="formRoleCode"
            placeholder="例如：PURCHASER"
            :maxlength="64"
            :disabled="!!editingRole"
          />
        </a-form-item>
        <a-form-item label="角色类型">
          <a-select v-model:value="formRoleType">
            <a-select-option
              v-for="t in roleTypeOptions"
              :key="t"
              :value="t"
            >
              {{ t }}
            </a-select-option>
          </a-select>
        </a-form-item>
        <a-form-item label="数据范围">
          <a-select v-model:value="formDataScope">
            <a-select-option
              v-for="s in dataScopeOptions"
              :key="s"
              :value="s"
            >
              {{ s }}
            </a-select-option>
          </a-select>
        </a-form-item>
        <a-form-item label="备注">
          <a-textarea
            v-model:value="formRemark"
            placeholder="角色描述"
            :rows="3"
          />
        </a-form-item>
      </a-form>
    </a-modal>
  </div>
</template>

<style scoped>
.role-editor-layout {
  display: flex;
  gap: 16px;
  height: calc(100vh - 160px);
}

.role-list-panel {
  width: 280px;
  min-width: 280px;
  background: #fff;
  border-radius: 8px;
  display: flex;
  flex-direction: column;
  overflow: hidden;
}

.permission-panel {
  flex: 1;
  background: #fff;
  border-radius: 8px;
  display: flex;
  flex-direction: column;
  overflow: hidden;
}

.panel-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 12px 20px;
  border-bottom: 1px solid #f0f0f0;
  gap: 12px;
}

.panel-header-left {
  flex-shrink: 0;
}

.panel-header-right {
  flex-shrink: 0;
}

.panel-title {
  font-size: 15px;
  font-weight: 600;
  color: #262626;
}

.role-list {
  flex: 1;
  overflow-y: auto;
  padding: 8px;
}

.role-item {
  padding: 12px 16px;
  border-radius: 8px;
  cursor: pointer;
  margin-bottom: 4px;
  transition: all 0.2s;
  border: 1px solid transparent;
}

.role-item:hover {
  background: #f5f5f5;
}

.role-item.active {
  background: #e6f7ff;
  border-color: #91d5ff;
}

.role-item-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  margin-bottom: 4px;
}

.role-name {
  font-weight: 500;
  color: #262626;
}

.role-item-meta {
  display: flex;
  gap: 8px;
  font-size: 12px;
  color: #8c8c8c;
}

.role-item-actions {
  margin-top: 8px;
}

.role-edit-link {
  display: inline-flex;
  align-items: center;
  gap: 4px;
  font-size: 12px;
  color: #1890ff;
  cursor: pointer;
  user-select: none;
  padding: 2px 0;
}

.role-edit-link:hover {
  color: #40a9ff;
}

/* 列表视图 */
.menu-tree {
  flex: 1;
  overflow-y: auto;
  padding: 16px 20px;
}

.menu-group {
  margin-bottom: 16px;
}

.menu-group-header {
  padding: 8px 0;
  border-bottom: 1px solid #f0f0f0;
  margin-bottom: 8px;
}

.menu-group-title {
  font-size: 14px;
  font-weight: 600;
  color: #262626;
}

.menu-item-row {
  display: flex;
  align-items: center;
  padding: 6px 0 6px 16px;
  border-radius: 4px;
  transition: background 0.2s;
}

.menu-item-row:hover {
  background: #fafafa;
}

.menu-item-header {
  width: 160px;
  flex-shrink: 0;
}

.menu-item-name {
  font-weight: 500;
}

.action-checkboxes {
  display: flex;
  gap: 16px;
  flex-wrap: wrap;
}

/* 矩阵视图 */
.matrix-view {
  flex: 1;
  overflow: hidden;
  padding: 12px;
}

.matrix-col-header {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 2px;
}

.matrix-col-header span {
  font-size: 12px;
}

.matrix-unsupported {
  color: #d9d9d9;
  text-align: center;
}
</style>
