// src/components/DataTable.tsx
import { type ReactNode } from 'react'
import { flexRender, type Table, type Row } from '@tanstack/react-table'
import { Spin, Empty } from 'antd'
import { LoadingOutlined } from '@ant-design/icons'
import './data-table.css'

interface DataTableProps<TData> {
  table: Table<TData>
  loading?: boolean
  bordered?: boolean
  size?: 'small' | 'middle' | 'default'
  emptyText?: string
  onRowClick?: (row: Row<TData>) => void
  expandedRowRender?: (row: Row<TData>) => ReactNode
  summaryRender?: () => ReactNode
}

export function DataTable<TData>({
  table,
  loading = false,
  bordered = false,
  size = 'default',
  emptyText = '暂无数据',
  onRowClick,
  expandedRowRender,
  summaryRender,
}: DataTableProps<TData>) {
  const sizeClass =
    size === 'small'
      ? 'leo-data-table-small'
      : size === 'middle'
        ? 'leo-data-table-middle'
        : ''

  const handleRowClick = (row: Row<TData>) => {
    if (onRowClick) {
      // Don't trigger on interactive elements
      onRowClick(row)
    }
  }

  return (
    <div
      className={`leo-data-table-wrapper ${bordered ? 'leo-data-table-bordered' : ''} ${sizeClass}`}
    >
      <div className="leo-data-table">
        <table
          style={{
            tableLayout: 'auto',
            borderCollapse: 'separate',
            borderSpacing: 0,
          }}
        >
          <thead>
            {table.getHeaderGroups().map((headerGroup) => (
              <tr key={headerGroup.id}>
                {headerGroup.headers.map((header) => {
                  const meta = header.column.columnDef.meta as
                    | Record<string, string>
                    | undefined
                  const align = meta?.align || 'center'
                  const width = meta?.width
                  const fixed = meta?.fixed
                  const canSort = header.column.getCanSort()

                  return (
                    <th
                      key={header.id}
                      className={`leo-data-table-th ${canSort ? 'leo-data-table-sortable' : ''} ${fixed ? `leo-data-table-sticky-${fixed}` : ''} leo-data-table-align-${align}`}
                      style={{
                        width,
                        ...(fixed === 'left'
                          ? {
                              position: 'sticky',
                              left: 0,
                              zIndex: 2,
                              background: '#fafafa',
                            }
                          : {}),
                        ...(fixed === 'right'
                          ? {
                              position: 'sticky',
                              right: 0,
                              zIndex: 2,
                              background: '#fafafa',
                            }
                          : {}),
                      }}
                      onClick={
                        canSort
                          ? header.column.getToggleSortingHandler()
                          : undefined
                      }
                    >
                      <div
                        style={{
                          display: 'flex',
                          alignItems: 'center',
                          justifyContent:
                            align === 'center'
                              ? 'center'
                              : align === 'right'
                                ? 'flex-end'
                                : 'flex-start',
                        }}
                      >
                        {flexRender(
                          header.column.columnDef.header,
                          header.getContext(),
                        )}
                        {canSort && (
                          <span className="leo-data-table-sorter">
                            <span
                              className={`leo-data-table-sorter-asc ${header.column.getIsSorted() === 'asc' ? 'leo-data-table-sorted-asc' : ''}`}
                            />
                            <span
                              className={`leo-data-table-sorter-desc ${header.column.getIsSorted() === 'desc' ? 'leo-data-table-sorted-desc' : ''}`}
                            />
                          </span>
                        )}
                      </div>
                    </th>
                  )
                })}
              </tr>
            ))}
          </thead>

          <tbody>
            {table.getRowModel().rows.length === 0 && !loading ? (
              <tr>
                <td
                  colSpan={table.getVisibleFlatColumns().length}
                  className="leo-data-table-td leo-data-table-empty"
                >
                  <Empty
                    description={emptyText}
                    image={Empty.PRESENTED_IMAGE_SIMPLE}
                  />
                </td>
              </tr>
            ) : (
              table
                .getRowModel()
                .rows.map((row) => (
                  <DataRow
                    key={row.id}
                    row={row}
                    onClick={handleRowClick}
                    expandedRowRender={expandedRowRender}
                  />
                ))
            )}
          </tbody>

          {summaryRender && (
            <tfoot>
              <tr>
                <td
                  colSpan={table.getVisibleFlatColumns().length}
                  className="leo-data-table-td"
                >
                  {summaryRender()}
                </td>
              </tr>
            </tfoot>
          )}
        </table>

        {loading && (
          <div className="leo-data-table-loading-overlay">
            <Spin indicator={<LoadingOutlined />} />
          </div>
        )}
      </div>
    </div>
  )
}

function DataRow<TData>({
  row,
  onClick,
  expandedRowRender,
}: {
  row: Row<TData>
  onClick?: (row: Row<TData>) => void
  expandedRowRender?: (row: Row<TData>) => ReactNode
}) {
  const isSelected = row.getIsSelected()
  const isExpanded = row.getIsExpanded()

  return (
    <>
      <tr
        className={`leo-data-table-row ${isSelected ? 'leo-data-table-row-selected' : ''} ${onClick ? 'leo-data-table-row-selectable' : ''}`}
        onClick={() => onClick?.(row)}
      >
        {row.getVisibleCells().map((cell) => {
          const meta = cell.column.columnDef.meta as
            | Record<string, string>
            | undefined
          const align = meta?.align || 'center'
          const fixed = meta?.fixed
          const ellipsis = meta?.ellipsis

          return (
            <td
              key={cell.id}
              className={`leo-data-table-td ${fixed ? `leo-data-table-sticky-${fixed}` : ''} leo-data-table-align-${align} ${ellipsis ? 'leo-data-table-cell-ellipsis' : ''}`}
              style={{
                ...(fixed === 'left'
                  ? {
                      position: 'sticky',
                      left: 0,
                      zIndex: 1,
                      background: isSelected ? '#e6f4ff' : '#fff',
                    }
                  : {}),
                ...(fixed === 'right'
                  ? {
                      position: 'sticky',
                      right: 0,
                      zIndex: 1,
                      background: isSelected ? '#e6f4ff' : '#fff',
                    }
                  : {}),
              }}
            >
              {flexRender(cell.column.columnDef.cell, cell.getContext())}
            </td>
          )
        })}
      </tr>

      {isExpanded && expandedRowRender && (
        <tr className="leo-data-table-expanded-row">
          <td
            colSpan={row.getVisibleCells().length}
            className="leo-data-table-td"
            style={{ padding: '16px 24px', background: '#fafafa' }}
          >
            {expandedRowRender(row)}
          </td>
        </tr>
      )}
    </>
  )
}

// src/components/DataTable.vue
<script setup lang="ts" generic="TData">
import './data-table.css'
import { computed, useSlots } from 'vue'
import { FlexRender, type Table, type Row, type ColumnDef, type Cell } from '@tanstack/vue-table'

const props = withDefaults(defineProps<{
  table: Table<TData>
  loading?: boolean
  bordered?: boolean
  size?: 'small' | 'middle' | 'default'
  rowClass?: (row: TData) => string
  rowProps?: (row: TData) => Record<string, unknown>
  emptyText?: string
  scrollX?: string | number
  scrollY?: string | number
}>(), {
  loading: false,
  bordered: true,
  size: 'default',
  rowClass: undefined,
  rowProps: undefined,
  scrollX: undefined,
  scrollY: undefined,
  emptyText: '暂无数据',
})

const slots = useSlots()

function getCellSlot(columnId: string): ((props: { row: TData; cell: Cell<TData, unknown> }) => unknown) | undefined {
  const slot = slots[`cell-${columnId}`]
  if (!slot) return undefined
  return ((scope: { row: TData; cell: Cell<TData, unknown> }) => slot(scope)) as unknown as (props: { row: TData; cell: Cell<TData, unknown> }) => unknown
}

const wrapperClass = computed(() => ({
  'leo-data-table-wrapper': true,
  'leo-data-table-bordered': props.bordered,
  'leo-data-table-small': props.size === 'small',
  'leo-data-table-middle': props.size === 'middle',
}))

const scrollStyle = computed(() => ({
  ...(props.scrollX ? { overflowX: 'auto' as const } : {}),
  ...(props.scrollY ? { maxHeight: typeof props.scrollY === 'number' ? `${props.scrollY}px` : props.scrollY, overflowY: 'auto' as const } : {}),
}))

function thClass(header: ReturnType<Table<TData>['getFlatHeaders']>[number]) {
  const col = header.column
  const meta = getColumnMeta(col.columnDef)
  return {
    'leo-data-table-th': true,
    'leo-data-table-sticky-left': meta.fixed === 'left',
    'leo-data-table-sortable': col.getCanSort(),
    [`leo-data-table-align-${meta.align || 'left'}`]: true,
    'leo-data-table-sorted-asc': col.getIsSorted() === 'asc',
    'leo-data-table-sorted-desc': col.getIsSorted() === 'desc',
  }
}

function tdClass(cell: ReturnType<Row<TData>['getVisibleCells']>[number]) {
  const meta = getColumnMeta(cell.column.columnDef)
  return {
    'leo-data-table-td': true,
    'leo-data-table-sticky-left': meta.fixed === 'left',
    [`leo-data-table-align-${meta.align || 'left'}`]: true,
    'leo-data-table-cell-ellipsis': meta.ellipsis === true,
  }
}

function getRowClasses(row: Row<TData>) {
  const classes: Record<string, boolean> = {
    'leo-data-table-row': true,
    'leo-data-table-row-selected': row.getIsSelected(),
  }
  if (props.rowClass) {
    const custom = props.rowClass(row.original)
    if (custom) classes[custom] = true
  }
  if (row.getIsExpanded()) {
    classes['leo-data-table-row-expanded'] = true
  }
  return classes
}

function getRowAttrs(row: Row<TData>) {
  const customProps = props.rowProps?.(row.original) || {}
  return {
    ...customProps,
    class: [getRowClasses(row), customProps.class],
  }
}

type ColumnMetaLike = { align?: 'left' | 'center' | 'right'; ellipsis?: boolean; fixed?: 'left' | 'right'; width?: number }

function getColumnMeta(column: ColumnDef<TData, unknown>): ColumnMetaLike {
  return (column.meta || {}) as ColumnMetaLike
}

function thStyle(header: ReturnType<Table<TData>['getFlatHeaders']>[number]) {
  const meta = getColumnMeta(header.column.columnDef)
  const style: Record<string, string> = {}
  if (meta.width) style.minWidth = `${meta.width}px`
  if (meta.fixed === 'left') {
    style.position = 'sticky'
    style.left = '0px'
    style.zIndex = '2'
  }
  return style
}

function tdStyle(cell: ReturnType<Row<TData>['getVisibleCells']>[number]) {
  const meta = getColumnMeta(cell.column.columnDef)
  const style: Record<string, string> = {}
  if (meta.width) style.minWidth = `${meta.width}px`
  if (meta.fixed === 'left') {
    style.position = 'sticky'
    style.left = '0px'
    style.zIndex = '1'
  }
  return style
}

const rows = computed(() => props.table.getRowModel().rows)
</script>

<template>
  <div :class="wrapperClass">
    <div class="leo-data-table" :style="scrollStyle">
      <table>
        <colgroup>
          <col
            v-for="header in table.getFlatHeaders()"
            :key="header.id"
            :style="getColumnMeta(header.column.columnDef).width ? { width: getColumnMeta(header.column.columnDef).width + 'px' } : undefined"
          />
        </colgroup>
        <thead class="leo-data-table-thead">
          <tr
            v-for="headerGroup in table.getHeaderGroups()"
            :key="headerGroup.id"
          >
            <th
              v-for="header in headerGroup.headers"
              :key="header.id"
              :class="thClass(header)"
              :style="thStyle(header)"
              :colspan="header.colSpan"
              @click="header.column.getToggleSortingHandler()?.({})"
            >
              <FlexRender
                v-if="!header.isPlaceholder"
                :render="header.column.columnDef.header"
                :props="header.getContext()"
              />
              <template v-if="header.column.getCanSort()">
                <span
                  :class="{
                    'leo-data-table-sorter': true,
                    'leo-data-table-sorter-active': header.column.getIsSorted(),
                  }"
                >
                  <span class="leo-data-table-sorter-asc" />
                  <span class="leo-data-table-sorter-desc" />
                </span>
              </template>
            </th>
          </tr>
        </thead>
        <tbody class="leo-data-table-tbody">
          <template v-if="rows.length === 0 && !loading">
            <tr>
              <td :colspan="table.getVisibleFlatColumns().length" class="leo-data-table-td leo-data-table-empty">
                <slot name="empty">
                  {{ emptyText }}
                </slot>
              </td>
            </tr>
          </template>
          <template v-for="row in rows" :key="row.id">
            <tr v-bind="getRowAttrs(row)">
              <td
                v-for="cell in row.getVisibleCells()"
                :key="cell.id"
                :class="tdClass(cell)"
                :style="tdStyle(cell)"
              >
                <slot
                  v-if="getCellSlot(cell.column.id)"
                  :name="`cell-${cell.column.id}`"
                  :row="row.original"
                  :cell="cell"
                />
                <FlexRender
                  v-else-if="cell.column.columnDef.cell"
                  :render="cell.column.columnDef.cell"
                  :props="cell.getContext()"
                />
              </td>
            </tr>
            <tr v-if="row.getIsExpanded()" class="leo-data-table-expanded-row">
              <td :colspan="row.getVisibleCells().length" class="leo-data-table-td">
                <slot name="expanded-row" :row="row" />
              </td>
            </tr>
          </template>
        </tbody>
      </table>
    </div>
    <div v-if="loading" class="leo-data-table-loading-overlay">
      <slot name="loading">
        <div class="leo-data-table-loading-spinner" />
      </slot>
    </div>
  </div>
</template>
