// src/components/PermButton.vue
<script setup lang="ts">
import { computed } from 'vue'
import { usePermissionStore } from '@/stores/permission'

const props = defineProps<{
  resource: string
  action: string
}>()

const permissionStore = usePermissionStore()

const visible = computed(() => permissionStore.can(props.resource, props.action))
</script>

<template>
  <a-button v-if="visible" v-bind="$attrs">
    <slot />
  </a-button>
</template>

// src/components/PermButton.tsx
import { Button, type ButtonProps } from 'antd'
import { usePermissionStore } from '@/stores/permissionStore'

interface PermButtonProps extends ButtonProps {
  resource: string
  action: string
  permissionStoreOverride?: { can: (resource: string, action: string) => boolean }
}

export function PermButton({
  resource,
  action,
  permissionStoreOverride,
  children,
  ...buttonProps
}: PermButtonProps) {
  const can = permissionStoreOverride?.can || usePermissionStore((s) => s.can)

  if (!can(resource, action)) {
    return null
  }

  return <Button {...buttonProps}>{children}</Button>
}
