// src/components/TableActions.tsx
import { Button, Popconfirm, Divider } from 'antd'
import type { ReactNode } from 'react'

export interface ActionItem {
  key: string
  label: string
  icon?: ReactNode
  danger?: boolean
  confirm?: string
  visible?: boolean
  disabled?: boolean
  onClick: () => void
}

interface Props {
  items: ActionItem[]
  maxVisible?: number
}

export function TableActions({ items, maxVisible }: Props) {
  const visible = items.filter((item) => item.visible !== false)
  if (visible.length === 0) {
    return <span className="table-action-empty">--</span>
  }

  const displayItems = maxVisible ? visible.slice(0, maxVisible) : visible

  return (
    <div className="table-action-group">
      {displayItems.map((item, index) => (
        <span key={item.key}>
          {index > 0 && <Divider type="vertical" />}
          {item.confirm ? (
            <Popconfirm title={item.confirm} onConfirm={item.onClick} okText="确定" cancelText="取消">
              <Button
                type="link"
                danger={item.danger}
                disabled={item.disabled}
                icon={item.icon}
                className="table-action-btn"
                size="small"
              >
                {item.label}
              </Button>
            </Popconfirm>
          ) : (
            <Button
              type="link"
              danger={item.danger}
              disabled={item.disabled}
              icon={item.icon}
              onClick={item.onClick}
              className={`table-action-btn ${item.danger ? 'table-action-danger' : ''} ${item.disabled ? 'table-action-disabled' : ''}`}
              size="small"
            >
              {item.label}
            </Button>
          )}
        </span>
      ))}
    </div>
  )
}

// src/components/TableActions.vue
<script setup lang="ts">
import type { Component } from 'vue'
import { computed } from 'vue'

export interface ActionItem {
  key: string
  label: string
  icon?: Component
  danger?: boolean
  confirm?: string
  visible?: boolean
  disabled?: boolean
  onClick: () => void
}

const props = withDefaults(defineProps<{
  items?: ActionItem[]
}>(), {
  items: () => []
})

const visibleItems = computed(() => props.items.filter(item => item.visible !== false))

const hasAnyVisible = computed(() => visibleItems.value.length > 0)
</script>

<template>
  <div v-if="hasAnyVisible" class="table-actions" @click.stop>
    <template v-for="(item, index) in visibleItems" :key="item.key">
      <a-divider v-if="index > 0" type="vertical" />
      <a-popconfirm
        v-if="item.confirm"
        :title="item.confirm"
        @confirm="item.onClick"
      >
        <span
          class="table-action-btn"
          :class="{
            'table-action-danger': item.danger,
            'table-action-disabled': item.disabled
          }"
          @click="!item.disabled && !item.confirm && item.onClick()"
        >
          <component :is="item.icon" v-if="item.icon" />
          <span>{{ item.label }}</span>
        </span>
      </a-popconfirm>
      <span
        v-else
        class="table-action-btn"
        :class="{
          'table-action-danger': item.danger,
          'table-action-disabled': item.disabled
        }"
        @click="!item.disabled && item.onClick()"
      >
        <component :is="item.icon" v-if="item.icon" />
        <span>{{ item.label }}</span>
      </span>
    </template>
  </div>
  <span v-else class="table-action-empty">--</span>
</template>
